# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BoostcampRelay23' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #Realm Lib Import
  pod 'RealmSwift'

  # Pods for BoostcampRelay23

  target 'BoostcampRelay23Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BoostcampRelay23UITests' do
    # Pods for testing
  end

end
